//! The sound played when a clip is saved.

use std::path::Path;

use windows::Win32::Media::Audio::{
    PlaySoundW, SND_ASYNC, SND_FILENAME, SND_MEMORY, SND_NODEFAULT,
};
use windows::core::{HSTRING, PCWSTR};

/// Trix's own chime, generated by `crates/trix-core/examples/make-chime.rs`.
///
/// Embedded rather than shipped as a sixth file in the release zip, which
/// would put it in the updater's `BINARIES`/`DOCS` lists and the
/// `SHA256SUMS.txt` flow for no gain. Being `'static` also happens to be what
/// makes `SND_MEMORY | SND_ASYNC` sound: that pair requires the buffer to
/// outlive playback, and a `'static` slice satisfies it by construction rather
/// than by careful lifetime management.
const BUILT_IN: &[u8] = include_bytes!("../assets/clip.wav");

/// Plays `custom` if it is there, and Trix's own chime otherwise.
///
/// Never returns an error, and that is deliberate: the only caller is the clip
/// path, where the clip is already written and broadcast by the time this runs.
/// A sound is feedback about a thing that already happened, so nothing here is
/// allowed to become the reason a clip reports failure.
///
/// `SND_ASYNC` returns as soon as playback is queued rather than when it
/// finishes, so this costs the clip path microseconds, not the length of the
/// sound. `SND_NODEFAULT` is what stops Windows substituting its own ding when
/// the file cannot be played -- without it, a broken sound is indistinguishable
/// from a working one to anybody debugging this.
pub fn play(custom: Option<&Path>) {
    let ok = match custom.filter(|path| path.exists()) {
        Some(path) => unsafe {
            PlaySoundW(&HSTRING::from(path), None, SND_FILENAME | SND_ASYNC | SND_NODEFAULT)
        },
        None => unsafe {
            PlaySoundW(
                PCWSTR(BUILT_IN.as_ptr().cast()),
                None,
                SND_MEMORY | SND_ASYNC | SND_NODEFAULT,
            )
        },
    };
    if !ok.as_bool() {
        tracing::warn!(sound = ?custom, "the clip sound could not be played");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The asset is embedded, so a corrupted or truncated commit of it would
    /// otherwise ship and simply never play. This is the only check that
    /// exists between the file in the repo and a silent release.
    #[test]
    fn the_built_in_chime_is_a_well_formed_wav() {
        assert!(trix_core::sound::looks_like_wav(BUILT_IN), "assets/clip.wav is not a WAV");
        assert!(BUILT_IN.len() > 1_000, "assets/clip.wav is suspiciously small");
        assert!(BUILT_IN.len() < 64 * 1024, "assets/clip.wav is too big to embed");
    }

    /// `play` must not panic when the cache it is handed is absent -- that is
    /// the ordinary state on a fresh install, and on the failure path where a
    /// conversion never landed. It falls back to the built-in.
    #[test]
    fn a_missing_cache_file_is_not_a_panic() {
        play(Some(std::path::Path::new(r"Z:\definitely\not\here.wav")));
    }
}
