//! The sound played when a clip is saved.

use std::path::Path;

use windows::Win32::Media::Audio::{
    PlaySoundW, SND_ASYNC, SND_FILENAME, SND_MEMORY, SND_NODEFAULT,
};
use windows::core::{HSTRING, PCWSTR};

/// Trix's own chime, generated by `crates/trix-core/examples/make-chime.rs`.
///
/// Embedded rather than shipped as a sixth file in the release zip, which
/// would put it in the updater's `BINARIES`/`DOCS` lists and the
/// `SHA256SUMS.txt` flow for no gain. Being `'static` also happens to be what
/// makes `SND_MEMORY | SND_ASYNC` sound: that pair requires the buffer to
/// outlive playback, and a `'static` slice satisfies it by construction rather
/// than by careful lifetime management.
const BUILT_IN_CLIP: &[u8] = include_bytes!("../assets/clip.wav");

/// Trix's screenshot blip, generated by
/// `crates/trix-core/examples/make-shot-sound.rs`. `'static` for the same
/// `SND_MEMORY | SND_ASYNC` reason as [`BUILT_IN_CLIP`].
const BUILT_IN_SHOT: &[u8] = include_bytes!("../assets/shot.wav");

/// Plays `custom` if it is there, and Trix's own chime otherwise.
///
/// Never returns an error, and that is deliberate: the only caller is the clip
/// path, where the clip is already written and broadcast by the time this runs.
/// A sound is feedback about a thing that already happened, so nothing here is
/// allowed to become the reason a clip reports failure.
///
/// `SND_ASYNC` returns as soon as playback is queued rather than when it
/// finishes, so this costs the clip path microseconds, not the length of the
/// sound. `SND_NODEFAULT` is what stops Windows substituting its own ding when
/// the file cannot be played -- without it, a broken sound is indistinguishable
/// from a working one to anybody debugging this.
pub fn play(custom: Option<&Path>) {
    // Resolved once and matched on again below for the failure log: which
    // branch actually played is what determines whose name belongs in the
    // warning, and `custom` alone does not say that -- a `custom` that does
    // not exist still falls through to the built-in chime, and blaming
    // `custom` for that chime's failure would point at the wrong file.
    let resolved = custom.filter(|path| path.exists());
    let ok = match resolved {
        Some(path) => unsafe {
            PlaySoundW(&HSTRING::from(path), None, SND_FILENAME | SND_ASYNC | SND_NODEFAULT)
        }
        .as_bool(),
        None => play_embedded(BUILT_IN_CLIP),
    };
    if !ok {
        match resolved {
            Some(path) => {
                tracing::warn!(sound = %path.display(), "the custom clip sound could not be played")
            }
            None => tracing::warn!("the built-in clip sound could not be played"),
        }
    }
}

/// Plays an embedded WAV.
///
/// Shared by [`play`]'s built-in branch and [`play_shot`] so both sounds get
/// the same flags: `SND_ASYNC` returns as soon as playback is queued rather
/// than when it finishes, and `SND_NODEFAULT` stops Windows substituting its
/// own ding when the file cannot be played -- without it, a broken sound is
/// indistinguishable from a working one to anybody debugging this.
fn play_embedded(wav: &[u8]) -> bool {
    unsafe {
        PlaySoundW(PCWSTR(wav.as_ptr().cast()), None, SND_MEMORY | SND_ASYNC | SND_NODEFAULT)
    }
    .as_bool()
}

/// Plays the screenshot blip.
///
/// No custom-file parameter, unlike [`play`]. The clip sound is replaceable
/// because it is the product's signature moment; a second picker, a second
/// cache and a second repair path is a great deal of surface for a sound that
/// plays a few times a session.
///
/// Never returns an error, for the same reason [`play`] does not: by the time
/// this runs the screenshot is already written, and a sound is feedback about
/// something that has already happened.
pub fn play_shot() {
    if !play_embedded(BUILT_IN_SHOT) {
        tracing::warn!("the screenshot sound could not be played");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The asset is embedded, so a corrupted or truncated commit of it would
    /// otherwise ship and simply never play. This is the only check that
    /// exists between the file in the repo and a silent release.
    #[test]
    fn the_built_in_chime_is_a_well_formed_wav() {
        assert!(trix_core::sound::looks_like_wav(BUILT_IN_CLIP), "assets/clip.wav is not a WAV");
        assert!(BUILT_IN_CLIP.len() > 1_000, "assets/clip.wav is suspiciously small");
        assert!(BUILT_IN_CLIP.len() < 64 * 1024, "assets/clip.wav is too big to embed");
    }

    /// The screenshot blip, held to the same bar as the clip chime: a corrupted
    /// or truncated commit of the asset would otherwise ship and simply never
    /// play.
    #[test]
    fn the_built_in_screenshot_sound_is_a_well_formed_wav() {
        assert!(trix_core::sound::looks_like_wav(BUILT_IN_SHOT), "assets/shot.wav is not a WAV");
    }

    /// Length is the primary way the two sounds are told apart mid-game. If the
    /// screenshot blip ever grows past the clip chime that distinction is gone,
    /// and this is the only place it would be noticed.
    #[test]
    fn the_screenshot_blip_stays_shorter_than_the_clip_chime() {
        assert!(BUILT_IN_SHOT.len() < BUILT_IN_CLIP.len());
    }

    /// `play` must not panic when the cache it is handed is absent -- that is
    /// the ordinary state on a fresh install, and on the failure path where a
    /// conversion never landed. It falls back to the built-in.
    #[test]
    fn a_missing_cache_file_is_not_a_panic() {
        play(Some(std::path::Path::new(r"Z:\definitely\not\here.wav")));
    }
}
